name: empire_lrp_helper
description: An Empire Larp Helper app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2

  # Intro slider
  intro_slider: ^4.0.0

  # MVVM
  get_it: ^7.2.0 # Simple dep injection
  provider: ^6.0.5 # View model provider

  shared_preferences: ^2.0.15 # Saving theme and start up using shared prefs
  flutter_shake_animated: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # App icon and splash screen
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: "^0.11.0"

  # MVVM


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/runes/Feresh.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# following page: https://dart.dev/tools/pub/pubspec


flutter_native_splash:
  color: "#881A72"
  image: "assets/runes/Feresh.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/dawnLogo.png
    - assets/settings.png
    - assets/home.png
    - assets/runes/Aesh.png
    - assets/runes/Bravash.png
    - assets/runes/Cavul.png
    - assets/runes/Diras.png
    - assets/runes/Evrom.png
    - assets/runes/Feresh.png
    - assets/runes/Gralm.png
    - assets/runes/Hirmok.png
    - assets/runes/Irremais.png
    - assets/runes/Jotra.png
    - assets/runes/Kyrop.png
    - assets/runes/Lann.png
    - assets/runes/Mawrig.png
    - assets/runes/Naeve.png
    - assets/runes/Ophis.png
    - assets/runes/Pallas.png
    - assets/runes/Queros.png
    - assets/runes/Rhyv.png
    - assets/runes/Sular.png
    - assets/runes/Tykonus.png
    - assets/runes/Ull.png
    - assets/runes/Verys.png
    - assets/runes/Wyr.png
    - assets/runes/Xun.png
    - assets/runes/Yoorn.png
    - assets/runes/Zorech.png
    - assets/runes/unnamed.png
    - assets/json/rune_card_list.json
    - assets/json/rune_details/aesh.json



  # Runes



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
